version: '2.2'

volumes:
  portainer:
  server:


networks:
  ct:

services:
  server:
    container_name: ct_server
    image: cherrytwist/server
    env_file:
      - .env
      - .env.default.env
    environment:
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - WAIT_HOSTS
      - WAIT_HOSTS_TIMEOUT
      - WAIT_SLEEP_INTERVAL
      - WAIT_HOST_CONNECT_TIMEOUT
    networks:
      - ct
    ports:
      - 4000:4000
    volumes:
      - server:/usr/src/app/config
    restart: always

  client:
    container_name: ct_client
    image: cherrytwist/client-web:latest
    env_file:
      - .env
    networks:
      - ct
    ports:
       - 80:80
    restart: always

  db:
    image: mysql:8.0.11
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    env_file:
      - .env
      - .env.default.env
    networks:
      - ct
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
      

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    env_file:
      - .env
    networks:
      - ct
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
