version: '2.1'

volumes:
  portainer:
  server:


networks:
  ct:

services:
  server:
    container_name: ct_server
    image: cherrytwist/server
    env_file:
      - .env
    networks:
      - ct
    ports:
      - 4000:4000
    volumes:
      - server:/usr/src/app/config
    restart: always

  client:
    container_name: ct_client
    image: cherrytwist/client-web:latest
    env_file:
      - .env
    networks:
      - ct
    ports:
       - 80:80
    restart: always


  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    env_file:
      - .env
    networks:
      - ct
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
