version: '2.3'

volumes:
  portainer:
  server:


networks:
  ct:

services:
  server:
    container_name: ct_server
    image: cherrytwist/server:0.1.5
    networks:
      - ct
    environment:
      - AUTHENTICATION_ENABLED
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - WAIT_HOSTS
      - WAIT_HOSTS_TIMEOUT
      - WAIT_SLEEP_INTERVAL
      - WAIT_HOST_CONNECT_TIMEOUT
    depends_on:
      - db
    restart: always
    ports:
      - 4000:4000
    command: sh -c "/wait && npm start"
    volumes:
      - server:/usr/src/app/config


  client:
    container_name: ct_client
    image: cherrytwist/client-web:v0.1.3
    networks:
      - ct
    environment:
      - REACT_AUTHENTICATION_ENABLE
    ports:
      - 80:80
    restart: always

  db:
    container_name: ct_server_db
    image: mysql:8.0.11
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - ct
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    networks:
      - ct
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
