version: '2.3'

volumes:
  portainer:
  server:


networks:
  ct:

services:
  server:
    container_name: ct_server
    image: cherrytwist/server:0.1.0
    environment:
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - WAIT_HOSTS
      - WAIT_HOSTS_TIMEOUT
      - WAIT_SLEEP_INTERVAL
      - WAIT_HOST_CONNECT_TIMEOUT
    networks:
      - ct
    ports:
      - 4000:4000
    volumes:
      - server:/usr/src/app/config
    restart: always

  client:
    container_name: ct_client
    image: cherrytwist/client-web:0.1.0
    networks:
      - ct
    ports:
       - 80:80
    restart: always

  db:
    image: mysql:8.0.11
    container_name: ct_server_db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    networks:
      - ct
    command: --default-authentication-plugin=mysql_native_password
    restart: always
      

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    networks:
      - ct
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
