version: '3.7'

networks:
  ct_demo_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

volumes:
  ct_demo_mysql_db:

services:
  mysql_db:
    container_name: ct_demo_mysql_db
    image: mysql:8.0.11
    networks:
      - ct_demo_net
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ct_demo_mysql_db:/var/lib/mysql
      - ./.scripts/schema.sql:/bootstrap_scripts/1.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /bootstrap_scripts/1.sql

  kratos_migrate:
    container_name: ct_demo_kratos_migrate
    image: oryd/kratos:v0.6.1-alpha.1
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
    restart: on-failure
    networks:
      - ct_demo_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    container_name: ct_demo_kratos
    image: oryd/kratos:v0.6.1-alpha.1
    depends_on:
      - kratos_migrate
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=mysql://root:${MYSQL_ROOT_PASSWORD}@tcp(${DATABASE_HOST}:3306)/kratos?max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://localhost:4433/
    networks:
      - ct_demo_net
    volumes:
      - type: bind
        source: ./.build/ory/kratos/email-password
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  oathkeeper:
    container_name: ct_demo_oathkeeper
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - ct_demo_net
    volumes:
      - ./.build/ory/oathkeeper:/etc/config/oathkeeper
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"

  ipfs:
    container_name: ct_demo_ipfs
    image: ipfs/go-ipfs
    networks:
      - ct_demo_net
    restart: always
    ports:
      - 4001:4001/tcp
      - 4002:4002/udp
      - 5001:5001
      - 8080:8080
    volumes:
      - /tmp/ipfs-docker-data:/data/ipfs

  ct_server:
    container_name: ct_demo_server
    image: cherrytwist/server:v0.11.5-alpha2
    depends_on:
      - mysql_db
      - ipfs
    networks:
      - ct_demo_net
    environment:
      - AUTH_ENABLED
      - NODE_ENV
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - WAIT_HOSTS=mysql_db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - GRAPHQL_ENDPOINT_PORT=4000
      - IPFS_ENDPOINT=http://ipfs:5001
      - IPFS_CLIENT_ENDPOINT=http://localhost:8080/ipfs
      - AUTH_ORY_KRATOS_ISSUER=http://cherrytwist-demo/
      - AUTH_ORY_KRATOS_JWKS_URI=http://oathkeeper:4456/.well-known/jwks.json
      - AUTH_ORY_KRATOS_PUBLIC_BASE_URL=http://localhost:4433/
      - AUTH_ORY_KRATOS_PUBLIC_BASE_URL_SERVER=http://kratos:4433/
      - CORS_ENABLED=false
      - LOGGING_LEVEL_CONSOLE=verbose
      - LOGGING_CONSOLE_ENABLED=true      -
    restart: always
    ports:
      - 4000:4000
    command: sh -c "/wait && /create_db.sh && npm run migration:run && npm start"

  ct_client:
    container_name: ct_demo_client
    image: cherrytwist/client-web:v0.8.1-alpha4p1
    networks:
      - ct_demo_net
    environment:
      - REACT_APP_SENTRY_ENABLED=false
      - REACT_APP_SENTRY_PII_ENABLED=false
      - REACT_APP_SENTRY_ENDPOINT
      - REACT_APP_FEEDBACK_URL=https://cherrytwist.org/feedback/
      - REACT_APP_GRAPHQL_ENDPOINT=http://localhost:4455/graphql
      - REACT_APP_BUILD_VERSION=dev
      - REACT_APP_VERSION=$npm_package_version
      - REACT_APP_NAME=$npm_package_name
    ports:
      - 3000:80
    restart: always


