http:
  services:
    alkemio-web-service:
      loadBalancer:
        servers:
          - url: "http://alkemio_client/"

    oathkeeper:
      loadBalancer:
        servers:
          - url: "http://oathkeeper:4455/"

    kratos-public:
      loadBalancer:
        servers:
          - url: "http://kratos:4433/"

    ipfs-http-adapter:
      loadBalancer:
        servers:
          - url: "http://ipfs:8080/"

  routers:
    graphql:
      rule: "PathPrefix(`/graphql`)"
      service: "oathkeeper"
      entryPoints:
        - "web"

    self-service:
      rule: "PathPrefix(`/self-service`)"
      service: "kratos-public"
      entryPoints:
        - "web"

    sessions:
      rule: "PathPrefix(`/sessions`)"
      service: "kratos-public"
      entryPoints:
        - "web"

    alkemiowebroute:
      rule: "PathPrefix(`/`)"
      service: "alkemio-web-service"
      entryPoints:
        - "web"

