# API and dashboard configuration
api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ':80'
  mariadb:
    address: ':3306'
  mailslurper-client:
    address: ':4436'
  mailslurper-api:
    address: ':4437'

providers:
  file:
    filename: /etc/traefik/http.yml
    watch: true

accessLog:
  filePath: '/etc/traefik/access.log'
