# API and dashboard configuration
api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  ipfs-http-adapter:
    address: ":80800" # not using for now
  kratos-public:
    address: ":44333" # not using for now

providers:
  file:
    filename: /etc/traefik/http.yml
    watch: true

accessLog:
  filePath: "/etc/traefik/access.log"

